set(temperature_sensor_controller_MESSAGE_FILES "/home/lewis/tiago_openday_ws/src/ros_controllers/temperature_sensor_controller/msg/ActuatorTemperatureState.msg")
set(temperature_sensor_controller_SERVICE_FILES "")
