// Generated by gencpp from file pal_walking_msgs/StepOverResponse.msg
// DO NOT EDIT!


#ifndef PAL_WALKING_MSGS_MESSAGE_STEPOVERRESPONSE_H
#define PAL_WALKING_MSGS_MESSAGE_STEPOVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_walking_msgs
{
template <class ContainerAllocator>
struct StepOverResponse_
{
  typedef StepOverResponse_<ContainerAllocator> Type;

  StepOverResponse_()
    : result()  {
    }
  StepOverResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StepOverResponse_

typedef ::pal_walking_msgs::StepOverResponse_<std::allocator<void> > StepOverResponse;

typedef boost::shared_ptr< ::pal_walking_msgs::StepOverResponse > StepOverResponsePtr;
typedef boost::shared_ptr< ::pal_walking_msgs::StepOverResponse const> StepOverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pal_walking_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'pal_walking_msgs': ['/home/lewis/tiago_openday_ws/src/pal_msgs/pal_walking_msgs/msg'], 'humanoid_nav_msgs': ['/home/lewis/tiago_openday_ws/src/humanoid_msgs/humanoid_nav_msgs/msg', '/home/lewis/tiago_openday_ws/devel/.private/humanoid_nav_msgs/share/humanoid_nav_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::pal_walking_msgs::StepOverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_walking_msgs/StepOverResponse";
  }

  static const char* value(const ::pal_walking_msgs::StepOverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string    result\n"
"\n"
;
  }

  static const char* value(const ::pal_walking_msgs::StepOverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepOverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_walking_msgs::StepOverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_walking_msgs::StepOverResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_WALKING_MSGS_MESSAGE_STEPOVERRESPONSE_H
